// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA5RNFE9Yp1Jj6Cgkmo3RKEo1k43TAmpY',
    appId: '1:12049475534:web:07afbd0f693752f4e9ad9f',
    messagingSenderId: '12049475534',
    projectId: 'partyloo-336302',
    authDomain: 'partyloo-336302.firebaseapp.com',
    storageBucket: 'partyloo-336302.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwbYEahezgp_b0ih1TB69jehjIeLgzT0Y',
    appId: '1:12049475534:android:e7a4697c4f255997e9ad9f',
    messagingSenderId: '12049475534',
    projectId: 'partyloo-336302',
    storageBucket: 'partyloo-336302.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYVfdp_Er6VStzXOdY1vOJa2CZMWshxCs',
    appId: '1:12049475534:ios:8c72f141d6c06f6ee9ad9f',
    messagingSenderId: '12049475534',
    projectId: 'partyloo-336302',
    storageBucket: 'partyloo-336302.appspot.com',
    androidClientId: '12049475534-a2iujuegoedoohgtsqtbqddur0dg7kn2.apps.googleusercontent.com',
    iosClientId: '12049475534-6q2ie3nj46ptm8jddes94sfqkaakvfcb.apps.googleusercontent.com',
    iosBundleId: 'com.example.partyx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYVfdp_Er6VStzXOdY1vOJa2CZMWshxCs',
    appId: '1:12049475534:ios:8c72f141d6c06f6ee9ad9f',
    messagingSenderId: '12049475534',
    projectId: 'partyloo-336302',
    storageBucket: 'partyloo-336302.appspot.com',
    androidClientId: '12049475534-a2iujuegoedoohgtsqtbqddur0dg7kn2.apps.googleusercontent.com',
    iosClientId: '12049475534-6q2ie3nj46ptm8jddes94sfqkaakvfcb.apps.googleusercontent.com',
    iosBundleId: 'com.example.partyx',
  );
}
