// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBOSkWTNnxEpJdslApp7cEh7opDulhbnw',
    appId: '1:363515450629:web:aaef44093893c9d64c536c',
    messagingSenderId: '363515450629',
    projectId: 'mychat-5d9a1',
    authDomain: 'mychat-5d9a1.firebaseapp.com',
    storageBucket: 'mychat-5d9a1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmk4uLP4UD2PL5Mw8XyotCoXGrS9NI0Os',
    appId: '1:363515450629:android:04c921305def0c854c536c',
    messagingSenderId: '363515450629',
    projectId: 'mychat-5d9a1',
    storageBucket: 'mychat-5d9a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDwuR2T9lJfjkX3egac21hg48hKqafwz0',
    appId: '1:363515450629:ios:899803561908f1454c536c',
    messagingSenderId: '363515450629',
    projectId: 'mychat-5d9a1',
    storageBucket: 'mychat-5d9a1.appspot.com',
    iosClientId: '363515450629-d735amoth6p8o8jfk23kk9lshaghuptd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
